import type { IntegrationIR } from '../integration.ts';

const LINE_SEPARATOR = String.fromCharCode(0x2028);
const PARAGRAPH_SEPARATOR = String.fromCharCode(0x2029);
const UNSAFE_IN_SCRIPT = new RegExp(`[<>&${LINE_SEPARATOR}${PARAGRAPH_SEPARATOR}]`, 'g');

/**
 * JSON serialization that is also a safe JavaScript literal: `<`, `>`, `&`
 * and U+2028/U+2029 are escaped so the output can be embedded anywhere,
 * including older engines where the separators terminate string literals.
 */
export function jsonForScript(value: unknown, indent = 2): string {
  return JSON.stringify(value, null, indent).replace(
    UNSAFE_IN_SCRIPT,
    (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`,
  );
}

/**
 * The runtime part of the override. It is plain ES5 so it runs in any host
 * that evaluates `function main(config)`. It never performs I/O.
 *
 * Order of operations: validate the config shape and ownership of every
 * provider in this namespace first, and only then mutate, so a thrown error
 * never leaves a half-modified config behind.
 */
const RUNTIME = `
  function fail(message) {
    throw new Error("[ruhomo] " + message);
  }
  function isPlainObject(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value);
  }
  function hasOwn(object, key) {
    return Object.prototype.hasOwnProperty.call(object, key);
  }
  function isOwnedProvider(definition) {
    if (!isPlainObject(definition)) return false;
    if (TRANSPORT === "http") {
      return definition.type === "http" && typeof definition.url === "string" && definition.url.indexOf(OWNER_MARKER) !== -1;
    }
    return definition.type === "inline" && definition.behavior === "classical" && Array.isArray(definition.payload);
  }
  function ruleSetProviderName(rule) {
    if (typeof rule !== "string") return null;
    var fields = rule.split(",");
    if (fields.length < 3 || fields[0].trim().toUpperCase() !== "RULE-SET") return null;
    return fields[1].trim();
  }

  if (!isPlainObject(config)) fail("config must be an object");
  var providers = config["rule-providers"];
  if (providers === undefined || providers === null) {
    providers = null;
  } else if (!isPlainObject(providers)) {
    fail("\\"rule-providers\\" must be a mapping");
  }
  var rules = config.rules;
  if (rules === undefined || rules === null) {
    rules = null;
  } else if (!Array.isArray(rules)) {
    fail("\\"rules\\" must be a list");
  }

  var previous = [];
  if (providers !== null) {
    for (var key in providers) {
      if (!hasOwn(providers, key) || key.indexOf(NAMESPACE) !== 0) continue;
      if (!isOwnedProvider(providers[key])) {
        fail("rule-provider \\"" + key + "\\" uses this override's namespace but was not generated by it; refusing to overwrite");
      }
      previous.push(key);
    }
  }

  var nextProviders = providers === null ? {} : providers;
  for (var i = 0; i < previous.length; i++) delete nextProviders[previous[i]];
  for (var j = 0; j < PROVIDERS.length; j++) nextProviders[PROVIDERS[j].name] = PROVIDERS[j].definition;

  var kept = [];
  if (rules !== null) {
    for (var k = 0; k < rules.length; k++) {
      var name = ruleSetProviderName(rules[k]);
      if (name !== null && name.indexOf(NAMESPACE) === 0) continue;
      kept.push(rules[k]);
    }
  }

  config["rule-providers"] = nextProviders;
  config.rules = RULES.concat(kept);
  return config;
`;

/**
 * Renders the JavaScript override (`function main(config)`). It is
 * idempotent for its own namespace: entries previously generated for the
 * same recipe are replaced, other entries are left untouched.
 */
export function generateJsOverride(ir: IntegrationIR): string {
  const header = [
    '// ruhomo addon override (JavaScript) for Sub-Store style override hosts',
    '// Merges rule-providers and prepends RULE-SET entries; original rules keep their order.',
    '// Idempotent for this namespace only; other providers and rules are never touched.',
    '// Every referenced outbound target must already exist in the config.',
  ];
  if (ir.transport === 'inline') {
    header.push('// 静态导出：规则以内联 payload 写入，不支持独立规则热更新；修改规则后需要重新应用覆写。');
  }
  const providers = ir.providers.map((p) => ({ name: p.name, definition: p.definition }));
  const indent = (s: string) => s.replace(/\n/g, '\n  ');
  return [
    ...header,
    'function main(config) {',
    `  var NAMESPACE = ${jsonForScript(ir.namespacePrefix)};`,
    `  var TRANSPORT = ${jsonForScript(ir.transport)};`,
    `  var OWNER_MARKER = ${jsonForScript(ir.ownerMarker)};`,
    `  var PROVIDERS = ${indent(jsonForScript(providers))};`,
    `  var RULES = ${indent(jsonForScript(ir.rules))};`,
    RUNTIME.replace(/^\n/, '').replace(/\n$/, ''),
    '}',
    '',
  ].join('\n');
}
